name: Zardosht Hodaie
markdown: kramdown
pygments: true

excerpt_separator: "<!-- excerpt-separator -->"


# this goes inside _config.yml. Change as required
navigation:
# - text: home
#   path: index.html
#   url: /index.html

# - text: about
#   path: about.html
#   url: /about.html

- text: about
  path: about
  url: /index.html


- text: projects
  path: projects
  url: projects


# - text: blog
#   path: blog
#   url: /blog.html

- text: c.v.
  path: cv
  url: cv